// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, debugPrint;
import 'package:dio/dio.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static Future<FirebaseOptions> get currentPlatform async {
    const configuredApiUrl = String.fromEnvironment('API_URL', defaultValue: '');
    final baseUrl = configuredApiUrl.trim().isNotEmpty
        ? configuredApiUrl.trim()
        : 'https://api.excellenceacademy.site/api/v1/';
        
    final dio = Dio(BaseOptions(
      baseUrl: baseUrl,
      connectTimeout: const Duration(seconds: 10),
      receiveTimeout: const Duration(seconds: 10),
    ));

    try {
      final response = await dio.get('config/client');
      if (response.statusCode == 200 && response.data['success'] == true) {
        final data = response.data['data']['firebase'];
        if (kIsWeb) {
          return _parseOptions(data['web']);
        }
        switch (defaultTargetPlatform) {
          case TargetPlatform.android:
            return _parseOptions(data['android']);
          case TargetPlatform.iOS:
            return _parseOptions(data['ios']);
          case TargetPlatform.macOS:
            return _parseOptions(data['macos']);
          case TargetPlatform.windows:
            throw UnsupportedError('DefaultFirebaseOptions have not been configured for windows.');
          case TargetPlatform.linux:
            throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux.');
          default:
            throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
        }
      } else {
        throw Exception('Server returned invalid config response');
      }
    } catch (e) {
      debugPrint('[FirebaseOptions] Failed to fetch config from server: $e');
      throw Exception('Failed to load Firebase configuration securely');
    }
  }

  static FirebaseOptions _parseOptions(Map<String, dynamic> json) {
    return FirebaseOptions(
      apiKey: json['apiKey'] ?? '',
      appId: json['appId'] ?? '',
      messagingSenderId: json['messagingSenderId'] ?? '',
      projectId: json['projectId'] ?? '',
      authDomain: json['authDomain'],
      databaseURL: json['databaseURL'],
      storageBucket: json['storageBucket'],
      measurementId: json['measurementId'],
      trackingId: json['trackingId'],
      deepLinkURLScheme: json['deepLinkURLScheme'],
      androidClientId: json['androidClientId'],
      iosClientId: json['iosClientId'],
      iosBundleId: json['iosBundleId'],
      appGroupId: json['appGroupId'],
    );
  }
}
